name: Build Patches

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build patches
        run: ./gradlew :patches:build --no-daemon

      - name: Upload patches
        uses: actions/upload-artifact@v4
        with:
          name: Nai64Patches
          path: patches/build/libs/*.mpp
          if-no-files-found: error
